Fix/deliberations fixes
BUUPE/interview pull request #129
Opened 2021-03-15 18:55 UTC by vitorvicente

Fixed two major issues with the deliberations:
- Prior data in the currentApplicationDeliberation localStorage would not have a match and crash
- When someone else updated an application the entire thing would fall back to the first application because we were storing the full application and not the UID

2021-03-15 19:46 UTC, ROODAY requested changes
Looks good overall, just those 2 comments I left earlier about the TODO and console.log. Might also be a good time to put some comments throughout the code, as now that I'm looking back at it a few months later it's hard to follow along, I can only imagine how hard it'd be for someone brand new to the codebase.

2021-03-15 19:46 UTC, ROODAY commented on src/components/Deliberation/InterviewerView.js
>      applications: [], // TODO: instead of loading all the applications by default, load their ids, then pass that id to application display/admin settings so they can handle accordingly
Can we remove this TODO now?

2021-03-15 19:46 UTC, ROODAY commented on src/components/Deliberation/InterviewerView.js
> +    console.log(currentApplication);
Let's get rid of this console.log if we're done testing

2021-03-15 19:56 UTC, vitorvicente commented
Yeah it was hard enough for me to figure out why we were storing the entire application in localhost instead of the uid as is, so I think I'm gonna just comment a lot of stuff everywhere in a different PR

I'll fix these two things up though

2021-03-16 00:54 UTC, ROODAY approved these changes

2021-03-16 00:54 UTC, merged